title: Advanced IR WS23
description: >- # this means to ignore newlines until "baseurl:"
  Project Highlights
# Build settings
remote_theme: socialcomplab/cayman
github:
  parent: https://socialcomplab.github.io/
